[project]
name = "cookiecutter-fortran"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.10"
cookiecutter = "*"
pytest = "*"

[tasks]
test = { cmd = "pytest -v test_template.py" }
