# Add your source files here
# Example:
# sources = files(
#   'main.f',
#   'module1.f',
#   'module2.f90',
# )

sources = files(
  # TODO: List your source files here
)

exe = executable(
                 '{{cookiecutter.name}}',
                 sources,
                 dependencies: extra_deps,
                 install: true
                )
